### ISSUE TITLE
CustomModuleSkeleton/Bootstrap not found

### ISSUE THREAD

**Issue by waqasra2022skipq** [adunsulag/oe-module-custom-skeleton#2]
When I try to enable this module it gives me a fatal error. 
"
Fatal error: Uncaught Error: Class "OpenEMR\Modules\CustomModuleSkeleton\Bootstrap" not found in C:\xampp\htdocs\openemr\interface\modules\custom_modules\oe-module-custom-skeleton\openemr.bootstrap.php:23 Stack trace: #0 C:\xampp\htdocs\openemr\src\Core\ModulesApplication.php(108): include() #1 C:\xampp\htdocs\openemr\src\Core\ModulesApplication.php(96): OpenEMR\Core\ModulesApplication->loadCustomModule(Array, Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 C:\xampp\htdocs\openemr\src\Core\ModulesApplication.php(70): OpenEMR\Core\ModulesApplication->bootstrapCustomModules(Object(Symfony\Component\EventDispatcher\EventDispatcher), 'C:/xampp/htdocs...') #3 C:\xampp\htdocs\openemr\interface\globals.php(620): OpenEMR\Core\ModulesApplication->__construct(Object(OpenEMR\Core\Kernel), 'C:/xampp/htdocs...', 'interface/modul...', 'zend_modules') #4 C:\xampp\htdocs\openemr\interface\main\tabs\main.php(19): require_once('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\openemr\interface\modules\custom_modules\oe-module-custom-skeleton\openemr.bootstrap.php on line 23
"

**Comment by adunsulag** [comment]
@waqasra2022skipq Sorry for the very long delay, but do you know what version of OpenEMR you were running on?  This likely happened because your autoloader wasn't running.  Also what version of the module were you running.

**Comment by sanjay-makwana** [comment]
i am facing same issue. My open emr version 7.0
php 8.0

![image](https://user-images.githubusercontent.com/84075497/206966303-8120f568-ea29-49ca-91ed-eb1be6a12620.png)

**Comment by sjpadgett** [comment]
This issue is now fixed as of issue close date.
